version: 0.2

phases:
  install:
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build